name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        target: ['22']
    uses: snapshot-labs/actions/.github/workflows/test.yml@main
    secrets: inherit
    with:
      target: ${{ matrix.target }}
      mysql_database_name: snapshot_relayer_test
      mysql_schema_path: ./src/schema.sql
